models/Issues.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "issues".
 *
 * @property integer $id
 * @property string $project
 * @property string $tracker
 * @property string $parent_task
 * @property string $status
 * @property string $priority
 * @property string $subject
 * @property string $author
 * @property string $assignee
 * @property string $updated
 * @property string $category
 * @property string $target_version
 * @property string $start_date
 * @property string $due_date
 * @property string $estimated_time
 * @property string $spent_time
 * @property integer $done
 * @property string $created
 * @property string $closed
 * @property string $related_issues
 * @property string $private
 */
class Issues extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'issues';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['spent_time'], 'number'],
            [['assignee', 'done'], 'integer'],
            [['project', 'parent_task'], 'string', 'max' => 3],
            [['tracker'], 'string', 'max' => 6],
            [['status', 'category', 'estimated_time'], 'string', 'max' => 11],
            [['priority'], 'string', 'max' => 9],
            [['subject'], 'string', 'max' => 72],
            [['author'], 'string', 'max' => 20],
            [['updated', 'created'], 'string', 'max' => 16],
            [['target_version', 'start_date', 'due_date', 'closed', 'related_issues'], 'string', 'max' => 10],
            [['private'], 'string', 'max' => 2]
        ];
    }

    public function getProfile(){
        return $this->hasOne(Profiles::className(), ['id' => 'assignee']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'project' => 'Project',
            'tracker' => 'Tracker',
            'parent_task' => 'Parent Task',
            'status' => 'Status',
            'priority' => 'Priority',
            'subject' => 'Subject',
            'author' => 'Author',
            'assignee' => 'Assignee',
            'updated' => 'Updated',
            'category' => 'Category',
            'target_version' => 'Target Version',
            'start_date' => 'Start Date',
            'due_date' => 'Due Date',
            'estimated_time' => 'Estimated Time',
            'spent_time' => 'Spent Time',
            'done' => 'Done',
            'created' => 'Created',
            'closed' => 'Closed',
            'related_issues' => 'Related Issues',
            'private' => 'Private',
        ];
    }
}

controllers/IssuesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\issues;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * IssuesController implements the CRUD actions for issues model.
 */
class IssuesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all issues models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => issues::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single issues model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new issues model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new issues();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing issues model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['project/view', 'id' => $model->project_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing issues model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the issues model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return issues the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = issues::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/issues/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\issues */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="issues-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'project')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tracker')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'parent_task')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'priority')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'author')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'assignee')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'updated')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'category')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'target_version')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_date')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'due_date')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'estimated_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'spent_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'done')->textInput() ?>

    <?= $form->field($model, 'created')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'closed')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'related_issues')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'private')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/issues/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\issues */

$this->title = 'Create Issues';
$this->params['breadcrumbs'][] = ['label' => 'Issues', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issues-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/issues/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use miloschuman\highcharts\Highcharts;

use yii\web\JsExpression;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Задачи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issues-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            // 'tracker',
            // 'status',
            // 'priority',
            [
                'attribute' => 'Task',
                'format' => 'raw',
                'value' => function($model){
                    return Html::a($model->subject, ['/issues/update', 'id' => $model->id]);
                }
            ],
            // 'author',
            'profile.name:text:Исполнитель',
            // 'updated',
            // 'category',
            // 'target_version',
            // 'start_date',
            // 'due_date',
            [
                'attribute' => 'Оценили',
                'value' => 'estimated_time',
                'pageSummary' => true
            ],
            [
                'attribute' => 'Реально',
                'value' => 'spent_time',
                'pageSummary' => true
            ],
            [
                'attribute' => 'Запас',
                'format' => 'raw',
                'value' => function ($model) {
                        return $model->estimated_time - $model->spent_time;
                },
                'pageSummary' => true
            ],
            // 'done:text:Done %',
            // 'created',
            // 'closed',
            // 'related_issues',
            // 'private',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
        'showPageSummary' => true
    ]); ?>

<?php
$statisticCounts = [];
$statisticHours = [];

foreach ($statisticData as $key => $statisticItem) {
    $statisticCounts[] = [
        'name' => $statisticItem['tracker'],
        'y' => (integer)$statisticItem['count'],
        'color' => new JsExpression("Highcharts.getOptions().colors[{$key}]") //set color
    ];
}

foreach ($statisticData as $key => $statisticItem) {
    $statisticHours[] = [
        'name' => $statisticItem['tracker'],
        'y' => (integer)$statisticItem['spent_time'],
        'color' => new JsExpression("Highcharts.getOptions().colors[{$key}]") //set color
    ];
}

?>

<?php echo Highcharts::widget([
    'scripts' => [
        'modules/exporting',
        'themes/grid-light',
    ],
    'options' => [
        'title' => [
            'text' => 'Графики',
        ],
        'labels' => [
            'items' => [
                [
                    'html' => 'Соотношение в количестве',
                    'style' => [
                        'left' => '115px',
                        'top' => '0px',
                        'color' => new JsExpression('(Highcharts.theme && Highcharts.theme.textColor) || "black"'),
                    ],
                ],
                [
                    'html' => 'Соотношение в часах',
                    'style' => [
                        'left' => '815px',
                        'top' => '0px',
                        'color' => new JsExpression('(Highcharts.theme && Highcharts.theme.textColor) || "black"'),
                    ],
                ],
            ],
        ],
        'series' => [
            [
                'type' => 'pie',
                'name' => 'Шт.',
                'data' => $statisticCounts,
                'center' => [190, 180],
                'size' => 300,
                'showInLegend' => false,
                'dataLabels' => [
                    'enabled' => true,
                ],
            ],
            [
                'type' => 'pie',
                'name' => 'Часов',
                'data' => $statisticHours,
                'center' => [850, 180],
                'size' => 300,
                'showInLegend' => false,
                'dataLabels' => [
                    'enabled' => true,
                ],
            ],
        ],
    ]
]);?>



<table class="table table-hovered table-striped table-bordered">
<?php foreach($statisticData as $statisticItem):?>
    <tr>
        <td>
            <b><?php echo $statisticItem['tracker'];?></b>
        </td>
        <td>
            <?php echo $statisticItem['count'];?> (<?php echo $statisticItem['spent_time'];?> часов)
        </td>
    </tr>
<?php endforeach; ?>
</table>

</div>

views/issues/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\issues */

$this->title = 'Update Issues: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Issues', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="issues-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/issues/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\issues */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Issues', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issues-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'project',
            'tracker',
            'parent_task',
            'status',
            'priority',
            'subject',
            'author',
            'assignee',
            'updated',
            'category',
            'target_version',
            'start_date',
            'due_date',
            'estimated_time',
            'spent_time',
            'done',
            'created',
            'closed',
            'related_issues',
            'private',
        ],
    ]) ?>

</div>